---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: web-hello
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: new-pipeline-1
        name: hello-deploy-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: web-hello
          - name: APP_GIT_URL
            value: $(params.git-repo-url)
          - name: APP_GIT_REVISION
            value: $(params.git-revision)
        pipelineRef:
          name: new-pipeline-1
        workspaces:
        - name: app-source
          persistentVolumeClaim:
            claimName: app-source-pvc
        - name: maven-settings
          emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: web-hello
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: web-hello
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: web-hello
    template:
      name: web-hello
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: web-hello
  name: el-web-hello
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-web-hello
    weight: 100
